### ISSUE TITLE
Support for math typesetting

### ISSUE THREAD

**Issue by airpaio** [DylanAllen/noiiice#26]
Would you be up for changing the Markdown parser to support math typesetting?

The current parser, `markedjs`, doesn't provide math typesetting out of the box, and I tried extending `marked` with this capability, but failed.

However, I did try changing the parser to `markdown-it`, and using one of `markdown-it's` third-party plugins, I was able to get some beautiful math typesetting seen in the image below. We still get the same style of Markdown and syntax highlighting with `highlightjs` that are currently available in Noiiice.
![image](https://user-images.githubusercontent.com/5142567/94806483-a0fe9400-03b3-11eb-98aa-d716ab1908d4.png)

If you would find this valuable to Noiiice, then I can prepare a pull request for it.

**Comment by DylanAllen** [comment]
That sounds great! I don't see any issue with switching to `markdown-it`. Open a PR and I will review it.

**Comment by DylanAllen** [comment]
Resolved by PR #28
