### ISSUE TITLE
Missing target domain name for non EDGE deployments not using Amazon Route 53

### ISSUE THREAD

**Issue by ehemmerlin** [DylanAllen/noiiice#7]
## Expected Behavior
For non EDGE deployments the "Target Domain Name" should be written to the sercrets.json file if the domain is not hosted in Amazon Route 53, because in this case a CNAME record has to be added manually to the DNS records.

## Current Behavior
At this time the "Target Domain Name" can be found in the AWS console under **API Gateway > Custom Domain Names** but is not present in secrets.json file. For EDGE deployments on the other hand a similar information is already written in this file.

## Possible Solution
The target domain name for EDGE deployments and REGIONAL deployments return values in different keys.

## Steps to Reproduce
1. Use a domain name not hosted in Amazon Route 53
2. Install and deploy noiiice like described in the README but in the eur stage (which is a REGIONAL endpoint)
3. At the end of **Deploy the serverless stack** the target domain name is not present in secrets.json file like expected

**Comment by DylanAllen** [comment]
Fixed and pushed to master. Thank you for reporting!
